id = "trae"
name = "Trae Theme"
version = "0.0.1"
schema_version = 1
authors = ["qsbye <2557877116@qq.com>"]
repository = "https://github.com/qsbye/zed.theme.trae"
description = "A theme for Zed Editor based on the Trae Editor Default Theme"
